ManBarberSalon/WebUI/Models/MakeReservationViewModel.cs
using System;
using System.Collections.Generic;
using Entities.Concrete;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace WebUI.Models
{
    public class MakeReservationViewModel
    {
        public List<Menu> Menus { get; set; } 
        public List<Time> Times { get; set; } 
        public List<string> DisabledTimes { get; set; } 
        public Menu Menu { get; set; }
        public Employee Employee { get; set; }

        public int TimeId { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
    }
}

ManBarberSalon/WebUI/Models/SearchReservationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Entities.Concrete;

namespace WebUI.Models
{
    public class SearchReservationViewModel
    {
        public Employee Employee { get; set; }
        public string Date { get; set; }
        public List<Employee> Employees { get; set; }

    }
}

ManBarberSalon/WebUI/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using Business.Abstract;
using DataAccess.Concrete.EntitiyFramework.Contexts;
using Entities.Concrete;
using Entities.Concrete.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    [Authorize]
    public class ReservationController : Controller
    {
        private IEmployeeService _employeeService;
        private IReservationSerivce _reservationSerivce;
        private IMenuService _menuService;
        private ITimeService _timeService;
        public ReservationController(IEmployeeService employeeService, IReservationSerivce reservationSerivce, IMenuService menuService, ITimeService timeService)
        {
            _employeeService = employeeService;
            _reservationSerivce = reservationSerivce;
            _menuService = menuService;
            _timeService = timeService;
        }


        public IActionResult MyReservations() 
        {
            int userId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var model = new ReservationDetailListViewModel()
            {
                ReservationDetails = _reservationSerivce.GetReservationDetail(userId)
            };
            return View(model);
        }

        public IActionResult SearchReservation() 
        {
            var model = new SearchReservationViewModel
            {
                Employees = _employeeService.GetActiveEmployees()
            };
            return View(model);
        }


        [HttpPost]
        public IActionResult MakeReservations(SearchReservationViewModel model)
        {
            if (model == null)
            {
                return RedirectToAction("SearchReservation");
            }

            var disabledTimesList = _reservationSerivce.GetReservationTime(model.Employee.Id, model.Date);

            List<string> disabledTimesNameList = new List<string>();

            foreach(var time in disabledTimesList)
            {
                disabledTimesNameList.Add(time.Name);
            }

            var model2 = new MakeReservationViewModel
            {
                Times = _timeService.GetAll(),
                Menus = _menuService.GetAll(),
                DisabledTimes = disabledTimesNameList,
                Employee = _employeeService.GetById(model.Employee.Id), 
                Date = model.Date, 
            };
            return View(model2);
        }


        [HttpPost]
        public IActionResult Complete(CompleteViewModel model)
        {

            var dt = _reservationSerivce.ConvertToDateTime(model.Date);
            int userId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            Reservation reservation = new Reservation()
            {
                AppUserId = userId,
                EmployeeId = model.Employee.Id,
                MenuId = model.Menu.Id,
                TimeId = model.TimeId,
                Date = dt,
                StatuId = 1,
                CanceledDate = null,
            };

            _reservationSerivce.AddReservation(reservation);
            return RedirectToAction("MyReservations");
        }

        [HttpPost]
        public IActionResult CancelReservation(int reservationId)
        {
            _reservationSerivce.CancelReservation(reservationId);
            return RedirectToAction("MyReservations");
        }

    }
}

ManBarberSalon/WebUI/Views/Reservation/MakeReservations.cshtml
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@model MakeReservationViewModel
@{
    Layout = "ReservationLayout";
    ViewData["Title"] = "Randevu Al";
}

@section Css{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" type="text/css" />
}

<div class="inner-banner" id="home">
    <div class="inner-banner-overlay">
        <div class="container">
        </div>
    </div>
</div>


<div class="breadcrumb-agile">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Randevu Al</li>
        </ol>
    </div>
</div>


<div class="container" style="margin-top: 50px;">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="">Yapılacak işlemi Seçiniz</label>
                <select class="form-control custom-select" id="appointmentSelectedMenu">
                    <option value="" selected>Seçiniz</option>
                    @foreach (var menu in Model.Menus)
                    {
                        <option value="@menu.Id">@menu.Name</option>
                    }
                </select>
            </div>
        </div>
    </div>

</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            @foreach (var time in Model.Times)
            {
                if(Model.DisabledTimes.Contains(time.Name))
                {
                    <button type="button" class="btn btn-primary" disabled>@time.Name</button>
                }
                else
                {
                    <button type="button" class="btn btn-primary" data-toggle="modal" onclick="appointmentModalShow(event)" data-time-id="@time.Id">@time.Name</button>
                }
            }
        </div>
    </div>
</div>


<div class="modal fade" id="appointment" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form asp-controller="Reservation" asp-action="Complete" method="post">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Randevu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div class="form-group">
                        <label for="Employee">Personel</label>
                        <input asp-for="Employee.Id" type="hidden" class="form-control" value="@Model.Employee.Id">
                        <input type="text" class="form-control" value="@Model.Employee.FirstName @Model.Employee.LastName" disabled>
                    </div>
                    <div class="form-group">
                        <label for="appointmentMenuText">İşlem</label>
                        <input asp-for="Menu.Id" type="hidden" class="form-control" id="appointmentMenuId">
                        <input type="text" class="form-control" id="appointmentMenuText" disabled>
                    </div>
                    
                    <div class="form-group">
                        <label for="appointmentDate">Tarih</label>
                        <input asp-for="Date" type="hidden" class="form-control" value="@Model.Date">
                        <input type="text" class="form-control" id="appointmentDate" disabled="" value="@Model.Date">
                    </div>

                    <div class="form-group">
                        <label for="appointmentTimeText">Saat</label>
                        <input asp-for="TimeId" type="hidden" class="form-control" id="appointmentTimeId">
                        <input type="text" class="form-control" id="appointmentTimeText" disabled>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    <button type="submit" class="btn btn-primary">Randevu Onayla</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.tr.min.js" type="text/javascript"></script>

    <script type="text/javascript">

        $(document).ready(function() {
            $('#appointmentSelectedDate').datepicker({
                format: "dd.mm.yyyy",
                startDate: "-1d",
                endDate: "+20d",
                todayBtn: "linked",
                clearBtn: true,
                language: "tr",
                daysOfWeekDisabled: "0",
                autoclose: true,
                todayHighlight: true,
            });

        });

        function appointmentModalShow(event) {
            var appointmentSelectedMenu = $("#appointmentSelectedMenu option:selected").val();

            if (appointmentSelectedMenu != "") {
                $('#appointmentMenuText').val($("#appointmentSelectedMenu option:selected").text());
                $('#appointmentMenuId').val($("#appointmentSelectedMenu option:selected").val());
                $('#appointmentTimeId').val($(event.target).data('time-id'));
                $('#appointmentTimeText').val($(event.target).text());
                $('#appointment').modal('show');
            } else {
                confirm("Lütfen gerekli alanları doldurunuz.");
                $('#appointment').modal('hide');
            }
        }
    </script>
}

ManBarberSalon/WebUI/Views/Reservation/MyReservations.cshtml
@{
    Layout = "ReservationLayout";
    ViewData["Title"] = "Randevularım";
}

@model ReservationDetailListViewModel


<div class="inner-banner" id="home">
    <div class="inner-banner-overlay">
        <div class="container">
        </div>
    </div>
</div>

<div class="breadcrumb-agile">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Randevularım</li>
        </ol>
    </div>
</div>


@{
    int count = 1;
}

<div class="container table-responsive" style="padding-top: 50px;">
    <table class="table table-borderless">
        <thead>
            <tr>
                <th>#</th>
                <th>Personel</th>
                <th>Yapılacak iş</th>
                <th>Tarih</th>
                <th>Saat</th>
                <th>Durum</th>
                <th>İptal Edilme Tarihi</th>
                <th>İptal et</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var details in Model.ReservationDetails)
            {
                <tr>
                    <td>@count</td>
                    <td>@details.EmployeeFirstName @details.EmployeeLastName</td>
                    <td>@details.Menu</td>
                    <td>@details.Date</td>
                    <td>@details.Time</td>
                    @if (details.StatusId == 1)
                    {
                        <td class="table-success">@details.Status</td>
                        <td></td>
                        <td>
                            <button type="button" class="btn btn-warning" data-toggle="modal" onclick="cancelreservationmodelshow(event)" data-reservation-id="@details.ReservationId">
                                İptal Et
                            </button>
                        </td>
                    }
                    else
                    {
                        <td class="table-danger">@details.Status</td>
                        <td>@details.CanceledDate.Value.ToString("g")</td>
                        <td></td>
                    }
                </tr>
                count++;
            }
        </tbody>
    </table>
</div>


<div class="modal fade" id="cancelreservation" tabindex="-1" role="dialog" aria-labelledby="cancelreservationlabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form asp-action="CancelReservation" asp-controller="Reservation" method="post">
                <div class="modal-header">
                    <h5 class="modal-title" id="cancelreservationlabel">Randevu İptal</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Randevuyu iptal etmek üzeresiniz emin misiniz ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                    <button name="reservationId" id="selectedreservationId" type="submit" class="btn btn-primary">İptal Et</button>
                </div>
            </form>

        </div>
    </div>
</div>

                
<script type="text/javascript">

    function cancelreservationmodelshow(event) {

        $('#selectedreservationId').val($(event.target).data('reservation-id'));
        $('#cancelreservation').modal('show');
    }
</script>

ManBarberSalon/WebUI/Views/Reservation/SearchReservation.cshtml
@addTagHelper*, Microsoft.AspNetCore.Mvc.TagHelpers
@model SearchReservationViewModel
@{
    Layout = "ReservationLayout";
    ViewData["Title"] = "Randevu Ara";
}

@section Css{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" type="text/css" />
}



<div class="inner-banner" id="home">
    <div class="inner-banner-overlay">
        <div class="container">
        </div>
    </div>
</div>

<div class="breadcrumb-agile">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Randevu Ara</li>
        </ol>
    </div>
</div>


<div style="margin-top: 50px;" class="container">
    <form asp-controller="Reservation" asp-action="MakeReservations" method="post">
        <div class="row">
            <div class="col-sm">
                <div class="form-group">
                    <label for="">Personel Seçiniz</label>
                   <select asp-for="Employee.Id" class="form-control custom-select" id="emloyeeId">
                        <option value="" selected>Seçiniz</option>
                        @foreach (var employee in Model.Employees)
                        {
                            <option value="@employee.Id">@employee.FirstName @employee.LastName</option>

                        }
                    </select>
                </div>
            </div>
            <div class="col-sm">
                <div class="form-group">
                    <label for="appointmentSelectedDate">Tarih Seçiniz</label>
                    <input asp-for="Date" class="form-control" type="text" id="appointmentSelectedDate" value="" />
                </div>
            </div>
        </div>

        <input type="submit" onclick="return submitReservation()" value="Randevu Ara" class="btn btn-primary btn-group-sm float-right"/>
    </form>
</div>


@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.tr.min.js" type="text/javascript"></script>

    <script type="text/javascript">

        $(document).ready(function() {
            $('#appointmentSelectedDate').datepicker({
                format: "dd.mm.yyyy",
                startDate: "-1d",
                endDate: "+20d",
                todayBtn: "linked",
                clearBtn: true,
                language: "tr",
                daysOfWeekDisabled: "0",
                autoclose: true,
                todayHighlight: true,
            });

        });

        function submitReservation() {
            var employeeId = $("#emloyeeId option:selected").val();
            var appointmentSelectedDate = $("#appointmentSelectedDate").val();
            if (employeeId != "" && appointmentSelectedDate != "") {
                return true;
            } else {
                confirm("Lütfen gerekli alanları doldurunuz.");
                return false;
            }
        }
    </script>
}